baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Choeur & Orchestre"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

disableHostCheck= false

[taxonomies]
price = 0
adress = "adress"
startdate = 2019-01-30T18:30:24.144Z
enddate = 2019-01-30T18:30:24.144Z
youtube = "R5qHWnbyV3w"

sectionPagesMenu = "main"


[menu]

  # Main Menu
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1

    [[menu.main]]
    name = "Concerts"
    url = "/concerts/"
    weight = 2

    [[menu.main]]
    name = "Actualités"
    url = "/news/"
    weight = 3

    [[menu.main]]
    name = "Médias"
    url = "/medias/"
    weight = 3

     [[menu.main]]
    name = "Historique"
    url = "/timeline/"
    weight = 4

    # Footer Menu
    [[menu.footer]]
    name = "Mentions Légales"
    url = "/legals_mentions/"
    weight = 1

    [[menu.footer]]
    name = "Politique de confidentialité"
    url = "/privacy_policy/"
    weight = 2

    [[menu.footer]]
    name = "A propos"
    url = "/about/"
    weight = 3

    [params]
    [params.hero]
    title= "Choeur et Orchestre"
    subtitle = "Les Voix Unies"
    pre = "https://images.unsplash.com/photo-1547682724-509900da969a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1528&q=80"
